### ISSUE TITLE
Throws spurious errors when Steam is not running.

### ISSUE THREAD

**Issue by midspace** [Phoenix84/SEWorkshopTool#2]
When Steam is not running, it will still attempt to run.

Also, it should be noted that on Windows 8 and 10, that if Steam is running under UAC, SEWorkshopTool must also be run under UAC otherwise it will believe that Steam is not running, and fail.

**Comment by Phoenix84** [comment]
I can look into that.
But why would you run Steam elevated under UAC?

**Comment by Phoenix84** [comment]
Ugh, Trying to change the commit message just adds noise. I hate github.

**Comment by midspace** [comment]
I use UAC, because whenever I switch SE branches, I use MKLINK to create a symbolic link to the directory that I store that branch on. This saves me from having to redownload the entire branch delta.
MKLINK requires UAC to create a symbolic link.
The batch file I use will create links and then automatically restarts Steam.

Otherwise, some Steam users have had issues in the past when playing some games, and resort to starting Steam under UAC to fix it.

**Comment by midspace** [comment]
If there was a reliable way of de-elevating UAC to run Steam, I'd use it. I haven't found one.

**Comment by Phoenix84** [comment]
There is, I ran into the same problem, you can create junctions without admin permissions.
I actually updated the script on the forums with what I use, and I don't need admin.
http://forums.keenswh.com/threads/how-to-easily-switch-between-steam-branches-for-modding.7385481/

```
mklink /j SpaceEngineers SpaceEngineers.%BRANCH%
:: Swap the steam manifest
del ..\appmanifest_244850.acf
mklink /h ..\appmanifest_244850.acf ..\appmanifest_244850.acf.%BRANCH%
```

**Comment by midspace** [comment]
It looks like the `/h` for the hardlink on the .acf file does the trick. 👍

**Comment by Phoenix84** [comment]
...and hardlinks... :-)

It's a lot better than the directory copy of my first iteration. I can have open files (VS, explorer), and it still works.
