### ISSUE TITLE
Mod type 'Mod' does not match workshop 'mod'

### ISSUE THREAD

**Issue by szczepix** [Phoenix84/SEWorkshopTool#9]
I have error when updating my mod.
Mod name, folders and paths is right on 100%.

![Error catch](http://i.imgur.com/eIajawI.png)
![SEWT console](http://i.imgur.com/WKzvU9h.png)

**Comment by Phoenix84** [comment]
This was fixed in commit 747f35662ef64af6fac1ae394af13afd92fe79a7.

**Comment by szczepix** [comment]
Another exception:  https://1drv.ms/i/s!AgkzmGUN2mtGnyGEp0OxF2uJpl_d

**Comment by Phoenix84** [comment]
That is completely unrelated. Please open a new issue.
